### ISSUE TITLE
Temperature seems to default to bogus -99 degrees

### ISSUE THREAD

**Issue by fwenzel** [SunboX/mozweekend_AddOn_Demo#1]
![2015-07-16-17-09-26](https://cloud.githubusercontent.com/assets/87232/8753770/2c982792-2c73-11e5-8c50-3eb0fccb1a4d.png)

I activated the add-on, it did not show up. Then I rebooted which did make it show up, but with a bogus temperature.

Not sure where -99 degrees came from but I assume that wasn't the correct temperature that day.

**Comment by SunboX** [comment]
Hi, and thanks for your feedback! :smile: 

I couldn't reproduce, that it did not show up after activation. But I will keep an eye on it.

The -99°C are the initial "temperature". I'm using yahoo's weather API to get the current local temperature. Normally the -99°C should be updated after some seconds.

Sadly, yahoo seems to block some requests now. :disappointed_relieved: I can't even get the temperature on my device any more. But using this [fiddle](http://jsfiddle.net/SunboX/sjLktqsn/) still works.

I have to write to yahoo and ask for help / clarification. Don't know why this happens.

I will update the issue, if I get some more info.

**Comment by SunboX** [comment]
Ok, did some tests. Seems **NOT** to be a API rate limit. The console shows me the info `PositionError { code: 1, message: "User denied geolocation prompt" }` but I granted this permission before and it **did** work until yesterday. Without me doing anything, except restarting the phone.

Let's see if I can fix this.

**Comment by SunboX** [comment]
Hi, I've done some changes. Could you plz delete the addon and try to re-install it?

**Comment by fwenzel** [comment]
Seems to work now, thanks.

Side note: I hope the location icon is disappearing soon (I assume it means GPS is active which I really really don't want to be active all day).

Thanks!

**Comment by SunboX** [comment]
oh well, no device I know has a temperature sensor build in. So this addon needs your current location to get the local temperature from Yahoo's temperature API. You can set the interval - how often - the location and after that the API will be fetched / called.
